[package]
name = "modkit"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
ron.workspace = true
toml.workspace = true
thiserror.workspace = true
anyhow.workspace = true
sha2.workspace = true
walkdir.workspace = true