[package]
name = "core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bevy.workspace = true
bevy_replicon.workspace = true
serde.workspace = true
anyhow.workspace = true